# Generated by Django 3.1.5 on 2021-02-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean', models.CharField(max_length=300)),
                ('english', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('example', models.CharField(max_length=500, null=True)),
                ('explanation', models.CharField(max_length=500, null=True)),
                ('tags', models.ManyToManyField(to='myenglishmate.tag')),
            ],
        ),
    ]
