# Generated by Django 3.1.5 on 2021-08-25 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myenglishmate', '0002_auto_20210201_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='example',
        ),
        migrations.RemoveField(
            model_name='expression',
            name='explanation',
        ),
        migrations.AddField(
            model_name='expression',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expression',
            name='english',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='expression',
            name='korean',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='expression',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myenglishmate.Tag'),
        ),
    ]
