# Generated by Django 3.1.5 on 2021-09-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myenglishmate', '0010_auto_20210830_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expression',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myenglishmate.Tag'),
        ),
    ]
