# Generated by Django 3.1.5 on 2021-09-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myenglishmate', '0014_auto_20210906_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myenglishmate.Tag'),
        ),
    ]
