# Generated by Django 3.1.5 on 2021-09-06 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myenglishmate', '0018_auto_20210906_0455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'tagname')},
        ),
    ]
